sonar.organization=taylor-luttrell-williams-sonarsource
sonar.projectKey=taylor-luttrell-williams-sonarsource_aws-cli
sonar.projectName=aws-cli
sonar.host.url=https://sonarcloud.io

sonar.sources=awscli,arn_parser.py
sonar.tests=tests
sonar.python.version=3.9, 3.10, 3.11, 3.12, 3.13
sonar.sourceEncoding=UTF-8
