# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
import fnmatch
import json
import logging
import os
import re
import stat
import tempfile
import time
import zipfile

from awscli.customizations.lambdaweb import output
from awscli.customizations.lambdaweb.constants import (
    DEFAULT_INCLUDED_HIDDEN_DIRECTORIES,
    DEFAULT_INCLUDED_HIDDEN_FILES,
    ENTRY_POINT_CANDIDATES,
    FUNCTION_NAME_PATTERN,
    RUNTIME_ENTRY_FILE,
)
from awscli.customizations.lambdaweb.exceptions import (
    EntryPointNotFoundError,
    InvalidFunctionNameError,
    InvalidSourceError,
    MalformedPackageJsonError,
    WrapperConflictError,
)

logger = logging.getLogger(__name__)


# Wrapper injected as index.js. Uses dynamic import() because it is valid in
# both CJS and ESM contexts, so the wrapper works regardless of the project's
# module system without needing to detect or guess it.
WRAPPER_TEMPLATE = (
    "// Auto-generated by 'aws lambda-web deploy'. Loads your entry point.\n"
    "const entryPoint = {entry};\n"
    "import(entryPoint).catch((err) => {{\n"
    "  console.error(`Failed to load entry point ${{entryPoint}}:`, err);\n"
    "  process.exit(1);\n"
    "}});\n"
)


_FUNCTION_NAME_RE = re.compile(FUNCTION_NAME_PATTERN)


def _normalize_entry_path(path):
    return os.path.normpath(path).replace(os.sep, '/')


def _normalize_force_include(source_dir, paths):
    """Return validated ``--force-include`` paths in ZIP path form."""
    normalized_paths = set()
    for path in paths or ():
        normalized = os.path.normpath(path)
        if (
            not path
            or os.path.isabs(path)
            or normalized in ('.', '..')
            or normalized.startswith(f'..{os.sep}')
        ):
            raise InvalidSourceError(
                f"--force-include path '{path}' must be relative to --code "
                'and remain inside that directory.'
            )
        full_path = os.path.join(source_dir, normalized)
        if os.path.islink(full_path) or not os.path.isfile(full_path):
            raise InvalidSourceError(
                f"--force-include path '{path}' must identify a regular file "
                f"under --code '{source_dir}'. Directories, symlinks, and "
                "special files aren't supported."
            )
        normalized_paths.add(_normalize_entry_path(normalized))
    return normalized_paths


def resolve_entry_point(source_dir, explicit=None):
    """Resolve the entry point file inside ``source_dir``.

    Returns the entry path relative to ``source_dir``.
    """
    if explicit is not None:
        if os.path.isabs(explicit):
            raise InvalidSourceError(
                f"entry point '{explicit}' must be relative to source dir"
            )
        normalized = os.path.normpath(explicit)
        parts = normalized.split(os.sep)
        if '..' in parts:
            raise InvalidSourceError(
                f"entry point '{explicit}' escapes source dir"
            )
        candidate = os.path.join(source_dir, explicit)
        if not os.path.isfile(candidate):
            raise EntryPointNotFoundError(
                f"entry point '{explicit}' not found under {source_dir}"
            )
        return _normalize_entry_path(explicit)

    package_json_path = os.path.join(source_dir, 'package.json')
    if os.path.isfile(package_json_path):
        try:
            with open(package_json_path, encoding='utf-8-sig') as f:
                package = json.load(f)
        except ValueError as e:
            lineno = getattr(e, 'lineno', '?')
            colno = getattr(e, 'colno', '?')
            msg = getattr(e, 'msg', 'invalid JSON')
            raise MalformedPackageJsonError(
                f'package.json invalid at line {lineno}, column {colno}: {msg}'
            )
        except OSError as e:
            raise InvalidSourceError(
                f"Unable to read '{package_json_path}'. Check that the file "
                'is readable and try again.'
            ) from e
        if isinstance(package, dict):
            main = package.get('main')
            if isinstance(main, str):
                main_path = os.path.join(source_dir, main)
                if os.path.isfile(main_path):
                    return _normalize_entry_path(main)
            # Modern (esp. dual CJS/ESM) packages often declare only
            # "exports" and no "main". Consult the "." export as a fallback so
            # those resolve automatically instead of erroring / mis-detecting.
            exports = package.get('exports')
            if exports is not None:
                resolved = _resolve_from_exports(source_dir, exports)
                if resolved is not None:
                    return resolved

    for candidate in ENTRY_POINT_CANDIDATES:
        if os.path.isfile(os.path.join(source_dir, candidate)):
            return candidate

    candidates = ', '.join(ENTRY_POINT_CANDIDATES)
    raise EntryPointNotFoundError(
        f"No entry point was found under '{source_dir}'. The command checked: "
        f'{candidates}. Use --entry-point to specify one.'
    )


# Condition preference for package.json "exports": ESM first (matches the
# wrapper's dynamic import), then default, then CJS as last resort.
_EXPORT_CONDITION_PREFERENCE = (
    'import',
    'module',
    'default',
    'require',
    'node',
)


def _select_export_condition(value, _depth=0):
    """Reduce an ``exports`` value to a target string.

    ``value`` can be a target string, a fallback array, or a nested conditions
    object. Returns the first target string that matches the condition
    preference, or ``None``. The depth guard bounds pathological nesting.
    """
    if isinstance(value, str):
        return value
    if isinstance(value, list) and _depth < 8:
        for item in value:
            resolved = _select_export_condition(item, _depth + 1)
            if resolved is not None:
                return resolved
    if isinstance(value, dict) and _depth < 8:
        for cond in _EXPORT_CONDITION_PREFERENCE:
            if cond in value:
                resolved = _select_export_condition(value[cond], _depth + 1)
                if resolved is not None:
                    return resolved
    return None


def _resolve_from_exports(source_dir, exports):
    """Resolve the package's ``.`` entry from a package.json ``exports`` field.

    Returns a POSIX-relative path (for example, ``dist/index.js``) whose file
    exists under ``source_dir``, or ``None``.

    ``exports`` is used ONLY as a discovery heuristic to locate the main entry
    file; the injected wrapper imports that file by relative path, so Node's
    real ``exports`` conditional resolution never runs at deploy time. We just
    extract a plausible ``.`` target and confirm the file is present in the
    source tree so it is bundled. If it points at an unbuilt output (for
    example, a ``dist/`` directory that has not been generated yet), the file
    is absent and this function scans the entry-point candidates instead.
    Handles the common shapes::

        "exports": "./dist/index.js"
        "exports": {".": "./dist/index.js"}
        "exports": {".": {"import": "...", "require": "...", "default": "..."}}
        "exports": {"import": "...", "require": "...", "default": "..."}
        "exports": [null, "./dist/index.js"]

    A subpath map (keys beginning with ``.``) is only consulted for its ``.``
    entry; a bare conditions object (no ``.`` key) is resolved directly.
    """
    target = exports
    if isinstance(target, dict) and any(
        isinstance(k, str) and k.startswith('.') for k in target
    ):
        target = target.get('.')
    target = _select_export_condition(target)
    if not isinstance(target, str) or not target:
        return None
    # package.json paths are POSIX and usually './'-prefixed. Keep the '/'
    # form so the wrapper's import('./<entry>') stays valid, and reject any
    # absolute path or parent-dir escape.
    rel = target[2:] if target.startswith('./') else target
    if not rel or rel.startswith('/') or os.path.isabs(rel):
        return None
    if '..' in rel.split('/'):
        return None
    if os.path.isfile(os.path.join(source_dir, *rel.split('/'))):
        return rel
    return None


def _is_hidden(name):
    """Return True for a dotfile / dot-dir basename (but not '.'/'..')."""
    return name.startswith('.') and name not in ('.', '..')


def _inside_included_hidden_directory(rel_root):
    """Return True inside a hidden directory included by default."""
    if rel_root == '.':
        return False
    return any(
        part in DEFAULT_INCLUDED_HIDDEN_DIRECTORIES
        for part in rel_root.split('/')
    )


def _excluded(name, relpath, patterns):
    """Return True if a path component or its full relative path is excluded.

    ``name`` is the bare basename (dir or file); ``relpath`` is the path
    relative to the source root, with ``/`` separators. Single-segment
    patterns (``.git/``, ``*.pem``) are matched against the basename;
    multi-segment patterns (``node_modules/.cache/``) are matched against the
    full relative path or a suffix beginning at a path-component boundary.
    """
    for pat in patterns:
        check = pat.rstrip('/') if pat.endswith('/') else pat
        if not check:
            continue
        target = relpath if '/' in check else name
        # match case-insensitively on every platform so security patterns
        # like .env / *.pem cannot be bypassed with a different case on
        # case-sensitive filesystems.
        target = target.lower()
        check = check.lower()
        if fnmatch.fnmatch(target, check):
            return True
        if '/' in check and fnmatch.fnmatch(target, f'*/{check}'):
            return True
    return False


_SYMLINK_WARN_SAMPLE = 5
_HIDDEN_WARN_SAMPLE = 5


def _warn_skipped_symlinks(skipped_links):
    """Emit ONE consolidated warning naming symlinks left out of the bundle.

    Kept separate from the walk so ``build_zip`` reads cleanly and this stays
    unit-testable. No-op when nothing was skipped. Names up to
    :data:`_SYMLINK_WARN_SAMPLE` paths and calls out ``node_modules`` links
    specifically, since a pnpm / workspace layout is the usual reason deps go
    missing.
    """
    if not skipped_links:
        return
    sample = skipped_links[:_SYMLINK_WARN_SAMPLE]
    listed = ', '.join(sample)
    if len(skipped_links) > _SYMLINK_WARN_SAMPLE:
        listed += f', ... and {len(skipped_links) - _SYMLINK_WARN_SAMPLE} more'
    output.progress(
        f'Warning: skipped {len(skipped_links)} symlink(s) not followed into '
        f'the bundle: {listed}. Symlinks are never followed (they can escape '
        'the source directory or form cycles). If these are dependencies '
        '(for example, pnpm or workspace node_modules symlinks), '
        'the bundle may be missing modules; install with a layout that '
        'writes real files (for example, "npm install", or pnpm with '
        '"node-linker=hoisted") before deploying.'
    )


def _warn_skipped_hidden_paths(skipped_paths):
    """Emit one warning for hidden files and directories left out."""
    if not skipped_paths:
        return
    sample = skipped_paths[:_HIDDEN_WARN_SAMPLE]
    listed = ', '.join(sample)
    if len(skipped_paths) > _HIDDEN_WARN_SAMPLE:
        listed += f', ... and {len(skipped_paths) - _HIDDEN_WARN_SAMPLE} more'
    noun = 'path' if len(skipped_paths) == 1 else 'paths'
    output.progress(
        f'Warning: skipped {len(skipped_paths)} hidden {noun}: {listed}. '
        'Use --include-hidden-files to include hidden files and directories '
        "that don't match an exclusion pattern."
    )


def _warn_force_includes(paths):
    """Warn when files bypass the normal bundle exclusions."""
    if not paths:
        return
    listed = ', '.join(sorted(paths))
    output.progress(
        'Warning: The command includes these files as requested by '
        f'--force-include: {listed}. Verify that '
        "these files don't contain credentials or other secrets. Use AWS "
        'Secrets Manager for runtime secrets.'
    )


def _keep_dir(
    root,
    rel_root,
    name,
    exclude_patterns,
    include_hidden,
    skipped_links,
    skipped_hidden_paths,
):
    """Decide whether ``os.walk`` should descend into ``name``.

    Explicit exclusions take precedence. Included hidden directories and their
    descendants do not require the general hidden-file opt-in.
    """
    relpath = name if rel_root == '.' else f'{rel_root}/{name}'
    if _excluded(name, relpath, exclude_patterns):
        return False
    if (
        not include_hidden
        and _is_hidden(name)
        and name not in DEFAULT_INCLUDED_HIDDEN_DIRECTORIES
        and not _inside_included_hidden_directory(rel_root)
    ):
        skipped_hidden_paths.append(relpath)
        return False
    if os.path.islink(os.path.join(root, name)):
        # os.walk lists symlinked dirs under ``dirs`` even with
        # followlinks=False; prune so we neither descend nor add them, and
        # record the skip for the summary warning.
        skipped_links.append(relpath)
        return False
    return True


def build_zip(
    source_dir, entry, exclude_patterns, include_hidden, force_include=None
):
    """Build a zip from ``source_dir`` and return ``(temp_path, size)``.

    ``entry`` is the resolved entry-point path. When it is not ``index.js`` a
    generated ``index.js`` wrapper that dynamically imports it is added (the
    default deploy behavior). Pass ``entry=None`` to skip wrapper injection
    entirely -- used when the caller has selected the entry point out of band
    via a customer-set ``AWS_LAMBDA_NODEJS_ENTRYPOINT`` environment variable,
    so the runtime loads that file directly and a wrapper would be dead code.

    ``exclude_patterns`` excludes secrets, VCS metadata, and caches by default.
    ``force_include`` can override file exclusions for exact regular files,
    but it does not override hidden or excluded directories, symlinks, or
    special-file checks. Common hidden build and runtime paths are included by
    default. ``include_hidden`` controls other dotfiles and dot-directories.
    """
    forced_files = _normalize_force_include(source_dir, force_include)
    tmp = tempfile.NamedTemporaryFile(suffix='.zip', delete=False)
    tmp.close()
    temp_path = tmp.name
    try:
        _write_zip(
            temp_path,
            source_dir,
            entry,
            exclude_patterns,
            include_hidden,
            forced_files,
        )
    except BaseException:
        remove_bundle(temp_path)
        raise
    return temp_path, os.path.getsize(temp_path)


def remove_bundle(zip_path):
    """Delete a bundle produced by ``build_zip``; missing files are fine."""
    try:
        os.unlink(zip_path)
    except OSError:
        logger.debug('could not remove bundle %s', zip_path, exc_info=True)


def _write_zip(
    temp_path,
    source_dir,
    entry,
    exclude_patterns,
    include_hidden,
    forced_files,
):
    # Collect skipped symlinks; _warn_skipped_symlinks emits a summary after the walk.
    skipped_links = []
    skipped_hidden_paths = []
    bundled_paths = set()
    entry_arcname = None
    with zipfile.ZipFile(
        temp_path, mode='w', compression=zipfile.ZIP_DEFLATED
    ) as zf:
        for root, dirs, files in os.walk(source_dir, followlinks=False):
            rel_root = os.path.relpath(root, source_dir).replace(os.sep, '/')
            dirs[:] = [
                d
                for d in dirs
                if _keep_dir(
                    root,
                    rel_root,
                    d,
                    exclude_patterns,
                    include_hidden,
                    skipped_links,
                    skipped_hidden_paths,
                )
            ]
            for fn in files:
                full = os.path.join(root, fn)
                relpath = fn if rel_root == '.' else f'{rel_root}/{fn}'
                is_forced = relpath in forced_files
                if not is_forced and _excluded(fn, relpath, exclude_patterns):
                    continue
                if (
                    not is_forced
                    and not include_hidden
                    and _is_hidden(fn)
                    and fn not in DEFAULT_INCLUDED_HIDDEN_FILES
                    and not _inside_included_hidden_directory(rel_root)
                ):
                    skipped_hidden_paths.append(relpath)
                    continue
                if os.path.islink(full):
                    logger.debug('skipping symlink %s', full)
                    skipped_links.append(relpath)
                    continue
                if not os.path.isfile(full):
                    # FIFOs, sockets, and device nodes cannot be bundled --
                    # reading a FIFO would block the CLI forever.
                    output.progress(
                        f'Warning: skipping {relpath}: not a regular file.'
                    )
                    continue
                arcname = relpath
                zf.write(full, arcname)
                bundled_paths.add(arcname)
        missing_forced = sorted(forced_files - bundled_paths)
        if missing_forced:
            listed = ', '.join(f"'{path}'" for path in missing_forced)
            raise InvalidSourceError(
                "The command couldn't include these --force-include paths: "
                f'{listed}. Use --include-hidden-files if a parent directory '
                "is hidden. Files inside excluded or symlinked directories "
                "can't be included."
            )
        _warn_skipped_hidden_paths(skipped_hidden_paths)
        _warn_skipped_symlinks(skipped_links)
        if entry is not None:
            entry_arcname = _normalize_entry_path(entry)
            if entry_arcname not in bundled_paths:
                raise InvalidSourceError(
                    f"entry point '{entry}' is not included in the deployment "
                    'bundle. It may be hidden, excluded, a symlink, or not a '
                    'regular file. Choose an included file, use '
                    '--force-include for an excluded file, or use '
                    '--include-hidden-files for a hidden file.'
                )
        # ``entry is None`` means the caller selected the entry point out of
        # band (a customer-set AWS_LAMBDA_NODEJS_ENTRYPOINT environment
        # variable), so the runtime loads that file directly -- inject
        # nothing. Otherwise inject the index.js wrapper that imports the
        # resolved entry (the default).
        if entry_arcname is not None and entry_arcname != RUNTIME_ENTRY_FILE:
            existing = os.path.join(source_dir, RUNTIME_ENTRY_FILE)
            if RUNTIME_ENTRY_FILE in bundled_paths:
                raise WrapperConflictError(
                    f"Cannot inject wrapper: '{existing}' already exists. "
                    'Either rename your entry point to index.js, or '
                    'remove the existing index.js from the source '
                    'directory.'
                )
            zf.writestr(
                _wrapper_zipinfo(),
                WRAPPER_TEMPLATE.format(
                    entry=json.dumps(f'./{entry_arcname}')
                ),
            )

        _warn_force_includes(forced_files)


def _wrapper_zipinfo():
    # writestr's default entry mode is 0600, which the runtime may not be
    # able to read after extraction; give the wrapper world-readable 0644.
    info = zipfile.ZipInfo(RUNTIME_ENTRY_FILE, date_time=time.localtime()[:6])
    info.external_attr = (stat.S_IFREG | 0o644) << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    return info


def validate_function_name(name):
    """Raise ``InvalidFunctionNameError`` for an invalid web function name."""
    if not isinstance(name, str) or not _FUNCTION_NAME_RE.match(name):
        raise InvalidFunctionNameError(
            f"function name '{name}' is invalid: must be 2-64 characters, "
            'only alphanumeric, hyphens, and underscores, '
            'and must not start or end with a hyphen or underscore'
        )
