#!/usr/bin/env python
"""Script to create a pyinstaller executable.

This exe can then be wrapped in a platform specific installer for each
supported platform.
"""
import argparse
import os
import sys
import shutil
from distutils.dir_util import copy_tree

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import run, tmp_dir
from install_deps import install_packages


ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
EXE_DIR = os.path.join(ROOT, 'exe')
PYINSTALLER_DIR = os.path.join(EXE_DIR, 'pyinstaller')
ASSETS_DIR = os.path.join(EXE_DIR, 'assets')
DEFAULT_OUTPUT_ZIP = 'awscli-exe.zip'


def make_exe(exe_zipfile, cleanup=True):
    with tmp_dir() as workdir:
        delete_existing_exe_build()
        do_make_exe(workdir, exe_zipfile)
        if cleanup:
            cleanup_build()
    print('Exe build is available at: %s' % exe_zipfile)


def do_make_exe(workdir, exe_zipfile):
    exe_dir = os.path.join(workdir, 'aws')
    output_exe_dist_dir = os.path.join(exe_dir, 'dist')
    aws_exe_build = pyinstaller('aws.spec')
    copy_directory(aws_exe_build, output_exe_dist_dir)
    aws_complete_exe_build = pyinstaller('aws_completer.spec')
    copy_directory_contents_into(aws_complete_exe_build, output_exe_dist_dir)
    copy_directory_contents_into(ASSETS_DIR, exe_dir)
    save_to_zip(workdir, exe_zipfile)


def delete_existing_exe_build():
    build_dir = os.path.join(PYINSTALLER_DIR, 'dist')
    if os.path.isdir(build_dir):
        shutil.rmtree(build_dir)


def pyinstaller(specfile):
    aws_spec_path = os.path.join(PYINSTALLER_DIR, specfile)
    print(run('pyinstaller %s' % (aws_spec_path), cwd=PYINSTALLER_DIR))
    return os.path.join(
        PYINSTALLER_DIR, 'dist', os.path.splitext(specfile)[0])


def copy_directory(src, dst):
    print('Copying %s -> %s' % (src, dst))
    shutil.copytree(src, dst)


def copy_directory_contents_into(src, dst):
    print('Copying contents of %s into %s' % (src, dst))
    copy_tree(src, dst)


def save_to_zip(dirname, zipfile_name):
    if zipfile_name.endswith('.zip'):
        zipfile_name = zipfile_name[:-4]
    shutil.make_archive(zipfile_name, 'zip', dirname)


def cleanup_build():
    locations = [
        os.path.join(PYINSTALLER_DIR, 'build'),
        os.path.join(PYINSTALLER_DIR, 'dist'),
    ]
    for location in locations:
        shutil.rmtree(location)
        print('Deleted build directory: %s' % location)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--output',
        default=os.path.join(ROOT, 'dist', DEFAULT_OUTPUT_ZIP),
        help=(
            'The name of the file to save the exe zip. By default, '
            'this will be saved in "dist/%s" directory in the root of the '
            'awscli.' % DEFAULT_OUTPUT_ZIP
        )
    )
    parser.add_argument(
        '--no-cleanup',
        dest='cleanup',
        action='store_false',
        default=True,
        help=(
            'Leave the build folder produced by pyinstaller. This can be '
            'useful for debugging.'
        ),
    )
    parser.add_argument(
        '--src-dir',
        default=None,
        help=(
            'Source directory for pinned installation dependencies. This '
            'provides the ability to do offline builds without PyPI.'
        ),
    )
    args = parser.parse_args()

    output = os.path.abspath(args.output)
    if args.src_dir:
        print('Installing dependencies from local directory: %s' % args.src_dir)
        install_packages(args.src_dir)
    else:
        run('pip install -r requirements.txt')
        run('pip install .')

    make_exe(output, cleanup=args.cleanup)


if __name__ == "__main__":
    main()
