---
name: "AWS CLI v1-to-v2 Migration Tool Issue"
description: Report an issue or get support with the AWS CLI v1-to-v2 Migration Tool.
title: "(short issue description)"
labels: [v1-to-v2-migration-tool, needs-triage]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please see the [documentation](https://github.com/aws/aws-cli/tree/v1v2-migration-tool?tab=readme-ov-file#usage).
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: What is the problem? A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        All of the commands, arguments and their outputs used when trying to use the migration tool. Include snippets from the input script being linted if applicable. Anything else that might be relevant for troubleshooting this issue. Enter "N/A" if non-applicable.
    validations:
      required: true
  - type: input
    id: migration-tool-version
    attributes:
      label: Migration tool version used
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment details (OS name and version, etc.)
    validations:
        required: true
