#!/usr/bin/env python
"""Setup virtualenv to run check script"""
import os
import sys
from subprocess import check_call
import shutil

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
os.chdir(REPO_ROOT)


def run(command):
    return check_call(command, shell=True)


run('pip install -r requirements-check.txt')
