#!/usr/bin/env python
"""Script to run non-test checks on the codebase

Currently currently consists of only a manifest-check.
"""
from subprocess import check_call, Popen, PIPE


def run(command):
    return check_call(command, shell=True)


def main():
    run('check-manifest')


if __name__ == "__main__":
   main()
