#!/usr/bin/env python
import os
import sys
from contextlib import contextmanager
from subprocess import check_call

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))
RUN_TESTS_SCRIPTS = os.path.join(REPO_ROOT, 'scripts', 'ci', 'run-tests')


@contextmanager
def cd(path):
    """Change directory while inside context manager."""
    cwd = os.getcwd()
    try:
        os.chdir(path)
        yield
    finally:
        os.chdir(cwd)


def run(command):
    return check_call(command, shell=True)


if __name__ == "__main__":
    with cd(REPO_ROOT):
        if sys.version_info[:2] >= (3, 12):
            run("pip install setuptools==67.8.0")

        run("pip install -r requirements-dev-lock.txt")
