version: "0.2"
title: Create An AWS Lambda Function
description: This wizard will create a new AWS Lambda function for you
plan:
  basics:
    shortname: Intro
    description: Provide function name and runtime
    values:
      function_name:
        type: prompt
        description: Function name
      runtime:
        type: prompt
        description: Select the Lambda runtime
        choices:
          - actual_value: nodejs22.x
            display: Node.js 22
          - actual_value: nodejs20.x
            display: Node.js 20
          - actual_value: nodejs18.x
            display: Node.js 18
          - actual_value: python3.13
            display: Python 3.13
          - actual_value: python3.12
            display: Python 3.12
          - actual_value: python3.11
            display: Python 3.11
          - actual_value: python3.10
            display: Python 3.10
          - actual_value: python3.9
            display: Python 3.9
          - actual_value: java21
            display: Java 21
          - actual_value: java17
            display: Java 17
          - actual_value: java11
            display: Java 11
          - actual_value: java8.al2
            display: Java 8
          - actual_value: dotnet8
            display: .NET 8
          - actual_value: ruby3.4
            display: Ruby 3.4
          - actual_value: ruby3.3
            display: Ruby 3.3
          - actual_value: ruby3.2
            display: Ruby 3.2
          - actual_value: provided.al2023
            display: OS-only Runtime (Amazon Linux 2023)
          - actual_value: provided.al2
            display: OS-only Runtime (Amazon Linux 2)
  role:
    shortname: Permissions
    description: Provide Role to be used by Lmanbda function
    values:
      existing_roles:
        type: apicall
        operation: iam.ListRoles
        params: {}
        query: "sort_by(Roles[].{display: RoleName, actual_value: Arn}, &display)"
        cache: true
      role_arn:
        type: prompt
        description: Select the role to use
        choices: existing_roles
  handler:
    shortname: Handler
    description: Provide handler and code location
    values:
      handler:
        type: prompt
        description: Enter the handler for your function
      zip_filename:
        type: prompt
        completer: file_completer
        description: Enter location of your code zip file
  preview:
    shortname: Preview
    description: Preview results
    values:
      preview_cli_command_value:
        type: template
        value: |
          aws lambda create-function \
            --function-name '{function_name}' \
            --role '{role_arn}' \
            --runtime '{runtime}' \
            --handler '{handler}' \
            --zip-file fileb://{zip_filename}
      preview_cfn_template_value:
        type: template
        value: |
          Resources:
            {function_name}:
              Type: "AWS::Lambda::Function"
              Properties:
                FunctionName: {function_name}
                Runtime: {runtime}
                Handler: {handler}
                Role: {role_arn}
                Code:
                  # Replace the below properties after uploading code zip file to S3
                  S3Bucket: REPLACE-WITH-BUCKET-NAME
                  S3Key: REPLACE-WITH-KEY-NAME
      preview_value:
        type: template
        value: |
          {%if {preview_type} == preview_cli_command %}
          {preview_cli_command_value}
          {% endif %}
          {%if {preview_type} == preview_cfn_template %}
          {preview_cfn_template_value}
          {% endif %}
      preview_type:
        type: prompt
        description: Select an preview format
        choices:
          - display: None
            actual_value: preview_none
          - display: AWS CLI command
            actual_value: preview_cli_command
          - display: AWS CloudFormation template
            actual_value: preview_cfn_template
        details:
          value: preview_value
          visible: True
          description: "Preview"
  __DONE__:
execute:
  default:
    - type: apicall
      operation: lambda.CreateFunction
      output_var: function_arn
      query: FunctionArn
      params:
        FunctionName: "{function_name}"
        Role: "{role_arn}"
        Runtime: "{runtime}"
        Handler: "{handler}"
        Code:
          ZipFile:
            __wizard__:File:
              path: "{zip_filename}"
__OUTPUT__:
  value: |
    Wizard successfully created Lambda Function:
      Function name: {function_name}
      Function ARN: {function_arn}

    {% if {preview_type} == preview_cli_command %}
    Steps to create function is equivalent to running the following sample AWS CLI commands:

    {preview_cli_command_value}
    {% endif %}
    {% if {preview_type} == preview_cfn_template %}
    Steps to create function is equivalent to deploying the following sample AWS CloudFormation template:

    {preview_cfn_template_value}
    {% endif %}
