#!/usr/bin/env python
"""Generate the index used for the new auto-completion.

"""
import os

from awscli.autocomplete import indexer
from awscli.autocomplete.main import INDEX_DIR, INDEX_FILE
from awscli import clidriver


def main():
    if not os.path.isdir(INDEX_DIR):
        os.makedirs(INDEX_DIR)
    # Using a temporary name so if the index already exists, we'll
    # only replace the entire file once we successfully regenerate the
    # index.
    temp_name = '%s.temp' % INDEX_FILE
    db_connection = indexer.DatabaseConnection(temp_name)
    index = indexer.ModelIndexer(db_connection)
    driver = clidriver.create_clidriver()
    try:
        index.generate_index(driver)
    finally:
        db_connection.close()
    os.rename(temp_name, INDEX_FILE)


if __name__ == '__main__':
    main()
