name: Closed Issue Message
on:
    issues:
       types: [closed]
jobs:
    auto_comment:
        runs-on: ubuntu-latest
        steps:
        - uses: aws-actions/closed-issue-message@v2
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
                     This issue is now closed. Comments on closed issues are hard for our team to see. 
                     If you need more assistance, please open a new issue that references this one.
