name: PRs against master are not accepted, please target v2 branch

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail PRs against master
        run: |
          echo "PRs must be made against the v2 branch."
          exit 1
