name: Handle Non-labeled Issues

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  handle_non_labeled_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: aws-actions/handle-non-labeled-issues@d6b11a820a09b58180471df5be076df19f05b9dd # v1.0.1
        with:
          labels: needs-triage
