permissions:
  contents: read
  pages: write
  # Required per the following GH issue:
  # https://github.com/actions/deploy-pages/issues/9#issuecomment-1009157118
  # More details at:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write

name: Sphinx build

on:
  push:
    branches:
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # version 6.0.0
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # version 6.2.0
      with:
        python-version: "3.12"
        cache: pip
    - name: Install dependencies
      run: make install
    - name: Build docs
      run: make html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # version 5.0.0
      with:
        path: _build/html
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # version 5.0.0
