# Copyright 2013 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
"""Builtin CLI extensions.

This is a collection of built in CLI extensions that can be automatically
registered with the event system.

Plugin initialization is lazy: only the plugins relevant to the command
being invoked are imported and registered.  The mapping from command names
to plugins is maintained in awscli/handlers_registry.py, which is
auto-generated by scripts/generate_plugin_registry.

"""
import importlib

from awscli.handlers_registry import PLUGIN_REGISTRY

_SENTINEL_ALWAYS = '__always__'
_SENTINEL_MAIN = '__main__'


def _get_top_level_command(args):
    """Return the first non-flag, non-option-value token from args.

    args is the raw CLI argument list as passed to create_clidriver —
    i.e. sys.argv[1:] with the program name already stripped.

    Returns None if no positional argument is found (e.g. ['--version']).
    """
    skip_next = False
    for token in args:
        if skip_next:
            skip_next = False
            continue
        if token.startswith('--'):
            if '=' not in token:
                skip_next = True
            continue
        if token.startswith('-'):
            continue
        return token
    return None


def _get_top_level_command(args):
    """Return the first non-flag, non-option-value token from args."""
    skip_next = False
    for token in args:
        if skip_next:
            skip_next = False
            continue
        if token.startswith('--'):
            if '=' not in token:
                skip_next = True
            continue
        if token.startswith('-'):
            continue
        return token
    return None


def _call(entry, event_handlers):
    """Dispatch a single registry entry.

    Entry formats:
      (module, fn_name)              -- call fn(event_handlers)
      (module, fn_name, event_name)  -- event_handlers.register(event_name, fn)
    """
    module_path, fn_name = entry[0], entry[1]
    mod = importlib.import_module(module_path)
    fn = getattr(mod, fn_name)
    if len(entry) == 3:
        # Direct registration.  If fn is a class, instantiate it first
        # (e.g. ParamShorthandParser).
        handler = fn() if isinstance(fn, type) else fn
        event_handlers.register(entry[2], handler)
    else:
        fn(event_handlers)


def awscli_initialize(event_handlers, args=None):
    command = _get_top_level_command(args) if args is not None else None

    # Collect the set of entries to call, preserving order and deduplicating
    # so that entries shared across sentinels are only called once.
    seen = set()
    to_call = []

    def _enqueue(entries):
        for entry in entries:
            if entry not in seen:
                seen.add(entry)
                to_call.append(entry)

    _enqueue(PLUGIN_REGISTRY.get(_SENTINEL_ALWAYS, []))
    _enqueue(PLUGIN_REGISTRY.get(_SENTINEL_MAIN, []))

    if command is not None:
        # Load only the service-scoped plugins for the given command.
        _enqueue(PLUGIN_REGISTRY.get(command, []))
    else:
        # args was not provided — load all service-scoped plugins to ensure
        # nothing is missing. In production args is always provided via
        # create_clidriver(args); this path is hit only when a driver is
        # pre-created without args (e.g. in tests).
        for sentinel, entries in PLUGIN_REGISTRY.items():
            if sentinel not in (_SENTINEL_ALWAYS, _SENTINEL_MAIN):
                _enqueue(entries)

    for entry in to_call:
        _call(entry, event_handlers)
