# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# AUTO-GENERATED by scripts/generate_plugin_registry.
# DO NOT EDIT MANUALLY.
#
# Re-generate by running:
#   scripts/generate_plugin_registry
#
# Sentinels:
#   __always__  registered for every CLI invocation
#   __main__    registered when building the top-level command table
#   <service>   registered only when that service/command is invoked
#
# Entry formats:
#   (module, fn_name)              call fn(event_handlers)
#   (module, fn_name, event_name)  event_handlers.register(event_name, fn)

PLUGIN_REGISTRY = {
    '__always__': [
        ('awscli.paramfile', 'register_uri_param_handler', 'session-initialized'),
        ('awscli.customizations.binaryformat', 'add_binary_formatter', 'session-initialized'),
        ('awscli.clidriver', 'no_pager_handler', 'session-initialized'),
        ('awscli.argprocess', 'ParamShorthandParser', 'process-cli-arg'),
        ('awscli.customizations.s3errormsg', 'register_s3_error_msg'),
        ('awscli.customizations.addexamples', 'add_examples', 'doc-examples.*.*'),
        ('awscli.customizations.cliinput', 'register_cli_input_args'),
        ('awscli.customizations.streamingoutputarg', 'add_streaming_output_arg', 'building-argument-table.*'),
        ('awscli.customizations.globalargs', 'register_parse_global_args'),
        ('awscli.customizations.paginate', 'register_pagination'),
        ('awscli.customizations.ec2.secgroupsimplify', 'register_secgroup'),
        ('awscli.customizations.iamvirtmfa', 'IAMVMFAWrapper'),
        ('awscli.customizations.datapipeline', 'register_customizations'),
        ('awscli.customizations.ecs.monitormutatinggatewayservice', 'register_monitor_mutating_gateway_service'),
        ('awscli.customizations.cloudsearchdomain', 'register_cloudsearchdomain'),
        ('awscli.customizations.generatecliskeleton', 'register_generate_cli_skeleton'),
        ('awscli.customizations.assumerole', 'register_assume_role_provider'),
        ('awscli.customizations.waiters', 'register_add_waiters'),
        ('awscli.customizations.timestampformat', 'register_timestamp_format'),
        ('awscli.customizations.awslambda', 'register_lambda_create_function'),
        ('awscli.customizations.kms', 'register_fix_kms_create_grant_docs'),
        ('awscli.customizations.route53', 'register_create_hosted_zone_doc_fix'),
        ('awscli.customizations.iot_data', 'register_custom_endpoint_note'),
        ('awscli.customizations.cloudfront', 'register'),
        ('awscli.customizations.ec2.paginate', 'register_ec2_page_size_injector'),
        ('awscli.customizations.history', 'register_history_mode'),
        ('awscli.customizations.s3events', 'register_event_stream_arg'),
        ('awscli.customizations.s3events', 'register_document_expires_string'),
        ('awscli.customizations.sso', 'register_sso_commands'),
        ('awscli.customizations.dynamodb.paginatorfix', 'register_dynamodb_paginator_fix'),
        ('awscli.alias', 'register_alias_commands')
    ],
    'ec2': [
        ('awscli.customizations.ec2.decryptpassword', 'ec2_add_priv_launch_key', 'building-argument-table.ec2.get-password-data'),
        ('awscli.customizations.ec2.secgroupsimplify', 'register_secgroup'),
        ('awscli.customizations.ec2.bundleinstance', 'register_bundleinstance'),
        ('awscli.customizations.ec2.runinstances', 'register_runinstances'),
        ('awscli.customizations.removals', 'register_removals'),
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.toplevelbool', 'register_bool_params'),
        ('awscli.customizations.ec2.protocolarg', 'register_protocol_args')
    ],
    '__main__': [
        ('awscli.customizations.s3.s3', 's3_plugin_initialize'),
        ('awscli.customizations.dynamodb.ddb', 'register_ddb'),
        ('awscli.customizations.configure.configure', 'register_configure_cmd'),
        ('awscli.customizations.codedeploy.codedeploy', 'initialize'),
        ('awscli.customizations.configservice.rename_cmd', 'register_rename_config'),
        ('awscli.customizations.history', 'register_history_commands'),
        ('awscli.customizations.devcommands', 'register_dev_commands'),
        ('awscli.customizations.login', 'register_login_cmds')
    ],
    's3_sync': [
        ('awscli.customizations.s3.s3', 's3_plugin_initialize')
    ],
    'ses': [
        ('awscli.customizations.removals', 'register_removals'),
        ('awscli.customizations.sessendemail', 'register_ses_send_email')
    ],
    'emr': [
        ('awscli.customizations.removals', 'register_removals'),
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.emr.emr', 'emr_initialize')
    ],
    'kinesis': [
        ('awscli.customizations.removals', 'register_removals'),
        ('awscli.customizations.kinesis', 'register_kinesis_list_streams_pagination_backcompat')
    ],
    'lexv2-runtime': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'lambda': [
        ('awscli.customizations.removals', 'register_removals'),
        ('awscli.customizations.awslambda', 'register_lambda_create_function'),
        ('awscli.customizations.wizard.commands', 'register_wizard_commands')
    ],
    'sagemaker-runtime': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'bedrock-runtime': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'bedrock-agent-runtime': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'bedrock-agentcore': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'qbusiness': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'iotsitewise': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'logs': [
        ('awscli.customizations.removals', 'register_removals'),
        ('awscli.customizations.logs', 'register_logs_commands')
    ],
    'polly': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'connecthealth': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'devops-agent': [
        ('awscli.customizations.removals', 'register_removals')
    ],
    'rds': [
        ('awscli.customizations.rds', 'register_rds_modify_split'),
        ('awscli.customizations.rds', 'register_add_generate_db_auth_token')
    ],
    'rekognition': [
        ('awscli.customizations.rekognition', 'register_rekognition_detect_labels'),
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'dsql': [
        ('awscli.customizations.dsql', 'register_dsql_customizations')
    ],
    'cloudwatch': [
        ('awscli.customizations.putmetricdata', 'register_put_metric_data')
    ],
    'iam': [
        ('awscli.customizations.iamvirtmfa', 'IAMVMFAWrapper'),
        ('awscli.customizations.wizard.commands', 'register_wizard_commands')
    ],
    'swf': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'datapipeline': [
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.datapipeline', 'register_customizations')
    ],
    'cloudsearchdomain': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'sns': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'deploy': [
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.codedeploy.codedeploy', 'initialize')
    ],
    'codepipeline': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'kinesisanalytics': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'kinesisanalyticsv2': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'route53': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'gamelift': [
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.gamelift', 'register_gamelift_commands')
    ],
    'route53domains': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'apigateway': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'apigatewayv2': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'pinpoint': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'stepfunctions': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'clouddirectory': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'mturk': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'workdocs': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'lex-models': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'license-manager': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'eks': [
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.eks', 'initialize')
    ],
    'schemas': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'sagemaker': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'iotwireless': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'ecs': [
        ('awscli.customizations.argrename', 'register_arg_renames'),
        ('awscli.customizations.ecs', 'initialize'),
        ('awscli.customizations.ecs.monitormutatinggatewayservice', 'register_monitor_mutating_gateway_service')
    ],
    'controltower': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'glue': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'mgn': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'elasticache': [
        ('awscli.customizations.argrename', 'register_arg_renames')
    ],
    'cloudtrail': [
        ('awscli.customizations.cloudtrail', 'initialize')
    ],
    'ecr': [
        ('awscli.customizations.ecr', 'register_ecr_commands')
    ],
    'ecr-public': [
        ('awscli.customizations.ecr_public', 'register_ecr_public_commands')
    ],
    'cloudsearch': [
        ('awscli.customizations.cloudsearch', 'initialize')
    ],
    'emr-containers': [
        ('awscli.customizations.emrcontainers', 'initialize')
    ],
    'lightsail': [
        ('awscli.customizations.lightsail', 'initialize')
    ],
    'configservice': [
        ('awscli.customizations.configservice.subscribe', 'register_subscribe'),
        ('awscli.customizations.configservice.getstatus', 'register_get_status'),
        ('awscli.customizations.configservice.putconfigurationrecorder', 'register_modify_put_configuration_recorder')
    ],
    'codeartifact': [
        ('awscli.customizations.codeartifact', 'register_codeartifact_commands')
    ],
    'codecommit': [
        ('awscli.customizations.codecommit', 'initialize')
    ],
    'iot': [
        ('awscli.customizations.iot', 'register_create_keys_and_cert_arguments', 'building-argument-table.iot.create-keys-and-certificate'),
        ('awscli.customizations.iot', 'register_create_keys_from_csr_arguments', 'building-argument-table.iot.create-certificate-from-csr')
    ],
    'cloudfront': [
        ('awscli.customizations.cloudfront', 'register')
    ],
    'cloudformation': [
        ('awscli.customizations.cloudformation', 'initialize')
    ],
    'servicecatalog': [
        ('awscli.customizations.servicecatalog', 'register_servicecatalog_commands')
    ],
    'translate': [
        ('awscli.customizations.translate', 'register_translate_import_terminology')
    ],
    's3api': [
        ('awscli.customizations.s3events', 'register_event_stream_arg')
    ],
    'dlm': [
        ('awscli.customizations.dlm.dlm', 'dlm_initialize')
    ],
    'ssm': [
        ('awscli.customizations.sessionmanager', 'register_ssm_session')
    ],
    'cli-dev': [
        ('awscli.customizations.wizard.commands', 'register_wizard_commands')
    ],
    'configure': [
        ('awscli.customizations.wizard.commands', 'register_wizard_commands')
    ],
    'dynamodb': [
        ('awscli.customizations.wizard.commands', 'register_wizard_commands')
    ],
    'events': [
        ('awscli.customizations.wizard.commands', 'register_wizard_commands')
    ],
    'sso': [
        ('awscli.customizations.sso', 'register_sso_commands')
    ],
    'quicksight': [
        ('awscli.customizations.quicksight', 'register_quicksight_asset_bundle_customizations')
    ],
    'ec2-instance-connect': [
        ('awscli.customizations.ec2instanceconnect', 'register_ec2_instance_connect_commands')
    ]
}
